/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_pack;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author oSikaNi iSraeL
 */
public class Add_maintainace extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    int xMouse;
    int yMouse;
    /**
     * Creates new form Add_maintainace
     */
    public Add_maintainace() {
        initComponents();
         conn = java_connection.getConnection();
          maint_date.setVisible(false);
           maint_time.setVisible(false);
         currentDate();
         
         
         maintain_des.setBackground(new Color (0,0,0,0));
         maintain_amt.setBackground(new Color (0,0,0,0));
    
    }

    
    public void currentDate(){
    
    
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
   //     date_.setText(year+"/"+(month+1)+"/"+day);
        maint_date.setText(year+"/"+(month+1)+"/"+day);
  //  others_date_update.setText(year+"/"+(month+1)+"/"+day);
        

         Date date = new Date();
         String strDateFormat = "HH:mm:ss a";
         SimpleDateFormat sdf = new SimpleDateFormat(strDateFormat);
       //   time.setText(sdf.format(date));
          maint_time.setText(sdf.format(date));
     // others_time_update.setText(sdf.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        maintain_des = new javax.swing.JTextField();
        maintain_amt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        maint_date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        maint_time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 60));

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("Amount Used");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, -1, 60));

        maintain_des.setBackground(new java.awt.Color(204, 228, 202));
        maintain_des.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        maintain_des.setForeground(new java.awt.Color(0, 0, 0));
        maintain_des.setBorder(null);
        maintain_des.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maintain_desKeyPressed(evt);
            }
        });
        getContentPane().add(maintain_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 290, 50));

        maintain_amt.setBackground(new java.awt.Color(204, 228, 202));
        maintain_amt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        maintain_amt.setForeground(new java.awt.Color(0, 0, 0));
        maintain_amt.setBorder(null);
        maintain_amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maintain_amtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maintain_amtKeyTyped(evt);
            }
        });
        getContentPane().add(maintain_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 179, 170, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 170, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 152, 290, 10));
        getContentPane().add(maint_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 269, 130, 40));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_20px.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Checked_20px_2.png"))); // NOI18N
        jButton2.setText("Enter");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        maint_time.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(maint_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 246, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/31.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 1, true), "Maintenance Expenses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 24), new java.awt.Color(0, 51, 0))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 380));

        setSize(new java.awt.Dimension(491, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         if(maintain_des.getText().isEmpty() || maintain_amt.getText().isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Fill all Information","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {

            String sql = "Insert into maintenace(description, amt_used,  date_used, time_) values (?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1, maintain_des.getText());
            pst.setString(2, maintain_amt.getText());
            pst.setString(3, maint_date.getText());
            pst.setString(4, maint_time.getText());

            pst.execute();

            maintain_des.setText(null);
            maint_time.setText(null);
            maint_date.setText(null);
            maintain_amt.setText(null);

            JOptionPane.showMessageDialog(null," Success");

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null,"Check your internet connection");
        }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        expenses ex = new expenses();
        ex.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maintain_desKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maintain_desKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if(maintain_des.getText().isEmpty() || maintain_amt.getText().isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Fill all Information","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {

            String sql = "Insert into maintenace(description, amt_used,  date_used, time_) values (?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1, maintain_des.getText());
            pst.setString(2, maintain_amt.getText());
            pst.setString(3, maint_date.getText());
            pst.setString(4, maint_time.getText());

            pst.execute();

            maintain_des.setText(null);
            maint_time.setText(null);
            maint_date.setText(null);
            maintain_amt.setText(null);

            JOptionPane.showMessageDialog(null," Success");

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null,"Check your internet connection");
        }
         }
        }
    }//GEN-LAST:event_maintain_desKeyPressed

    private void maintain_amtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maintain_amtKeyPressed
        // TODO add your handling code here:
           if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if(maintain_des.getText().isEmpty() || maintain_amt.getText().isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Fill all Information","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {

            String sql = "Insert into maintenace(description, amt_used,  date_used, time_) values (?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1, maintain_des.getText());
            pst.setString(2, maintain_amt.getText());
            pst.setString(3, maint_date.getText());
            pst.setString(4, maint_time.getText());

            pst.execute();

            maintain_des.setText(null);
            maint_time.setText(null);
            maint_date.setText(null);
            maintain_amt.setText(null);

            JOptionPane.showMessageDialog(null," Success");

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null,"Check your internet connection");
        }
         }
        }
    }//GEN-LAST:event_maintain_amtKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
               setVisible(false);
        expenses ex = new expenses();
        ex.setVisible(true);
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void maintain_amtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maintain_amtKeyTyped
        // TODO add your handling code here:
        
         char check = evt.getKeyChar();
        
        if(!(Character.isDigit(check)
                || check ==KeyEvent.VK_ENTER 
                ||  check ==KeyEvent.VK_BACK_SPACE
                ||  check ==KeyEvent.VK_DELETE 
                || check ==KeyEvent.VK_PERIOD))
        {
        
            evt.consume();
           // JOptionPane.showMessageDialog(null, "Figures Only");
        }
    }//GEN-LAST:event_maintain_amtKeyTyped

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y-yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_maintainace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_maintainace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_maintainace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_maintainace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_maintainace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maint_date;
    private javax.swing.JTextField maint_time;
    private javax.swing.JTextField maintain_amt;
    private javax.swing.JTextField maintain_des;
    // End of variables declaration//GEN-END:variables
}
