/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_pack;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author oSikaNi iSraeL
 */
public class change_Password extends javax.swing.JFrame {
    
     Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form change_Password
     */
    public change_Password() {
        initComponents();
        
            conn = java_connection.getConnection();
              jLabel10.setVisible(false);
               jLabel7.setVisible(false);
               
               confirm.setBackground(new Color(0,0,0,0));
                new_pass.setBackground(new Color(0,0,0,0));
                 old_pass.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        confirm = new javax.swing.JTextField();
        old_pass = new javax.swing.JTextField();
        new_pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("HOSTEL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 42)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 0));
        jLabel8.setText("JODOK");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("New password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 0));
        jLabel3.setText("Confirm password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("Old password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Password_20px_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Attention_20px_2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Password_20px_5.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Ok_20px_1.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 230, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 230, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 230, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 230));

        confirm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        confirm.setForeground(new java.awt.Color(0, 0, 0));
        confirm.setBorder(null);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        confirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmKeyReleased(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 230, 40));

        old_pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        old_pass.setForeground(new java.awt.Color(0, 0, 0));
        old_pass.setBorder(null);
        old_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                old_passKeyPressed(evt);
            }
        });
        getContentPane().add(old_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 230, 40));

        new_pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        new_pass.setForeground(new java.awt.Color(0, 0, 0));
        new_pass.setBorder(null);
        new_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_passActionPerformed(evt);
            }
        });
        new_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_passKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                new_passKeyReleased(evt);
            }
        });
        getContentPane().add(new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 230, 40));

        jButton1.setBackground(new java.awt.Color(186, 218, 168));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 100, -1));

        jButton2.setBackground(new java.awt.Color(186, 218, 168));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh_15px.png"))); // NOI18N
        jButton2.setText("Change");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/31.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 1, true), "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 18), new java.awt.Color(0, 51, 0))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 320));

        setSize(new java.awt.Dimension(629, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jLabel1MouseClicked

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    private void new_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Fogort_password  fp = new Fogort_password();
        fp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

          
           String sql_1 = "select * from new_user where  user_password=?";
        try{
       
            
             String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         
             pst=conn.prepareStatement(sql_1);
            pst.setString(1, old_pass.getText());
         //   pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            
            
            if(rs.next() ){

                 int c = JOptionPane.showConfirmDialog(null,"Do you want to continue?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                
                String value1=confirm.getText();
          
               
                String old = old_pass.getText();
                String sql ="update new_user set user_password='"+value1+"' WHERE user_password='"+old+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Success");
                
                  }
                  catch (Exception e){
            
            }
                  
             }
                    new_pass.setText(null);
            old_pass.setText(null);
            confirm.setText(null);
               }

            else{
                
                JOptionPane.showMessageDialog(null, "Old Password Incorrect");
            
            }
        }
        
        else{
        
            JOptionPane.showMessageDialog(null, "New Password Incorrect");
        }
        
           
            
            
        }
            catch (Exception e){
            
            }
         
         
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmKeyReleased
        // TODO add your handling code here:
         String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         jLabel10.setVisible(true);
           jLabel7.setVisible(false);
        }
        else{
             jLabel7.setVisible(true);
            jLabel10.setVisible(false);
            
       //     JOptionPane.showMessageDialog(null, "erro");
        }
        
          
    }//GEN-LAST:event_confirmKeyReleased

    private void new_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_passKeyReleased
        // TODO add your handling code here:
     String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         jLabel10.setVisible(true);
           jLabel7.setVisible(false);
        }
        else{
             jLabel7.setVisible(true);
            jLabel10.setVisible(false);
            
           // JOptionPane.showMessageDialog(null, "erro");
        }
    }//GEN-LAST:event_new_passKeyReleased

    private void old_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_old_passKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            String sql_1 = "select * from new_user where  user_password=?";
        try{
       
            
             String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         
             pst=conn.prepareStatement(sql_1);
            pst.setString(1, old_pass.getText());
         //   pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            
            
            if(rs.next() ){

                 int c = JOptionPane.showConfirmDialog(null,"Do you want to continue?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                
                String value1=confirm.getText();
          
               
                String old = old_pass.getText();
                String sql ="update new_user set user_password='"+value1+"' WHERE user_password='"+old+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Success");
                
                  }
                  catch (Exception e){
            
            }
                  
             }
                    new_pass.setText(null);
            old_pass.setText(null);
            confirm.setText(null);
               }

            else{
                
                JOptionPane.showMessageDialog(null, "Old Password Incorrect");
            
            }
        }
        
        else{
        
            JOptionPane.showMessageDialog(null, "New Password Incorrect");
        }
        
           
            
            
        }
            catch (Exception e){
            
            }
        }
    }//GEN-LAST:event_old_passKeyPressed

    private void new_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_passKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            String sql_1 = "select * from new_user where  user_password=?";
        try{
       
            
             String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         
             pst=conn.prepareStatement(sql_1);
            pst.setString(1, old_pass.getText());
         //   pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            
            
            if(rs.next() ){

                 int c = JOptionPane.showConfirmDialog(null,"Do you want to continue?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                
                String value1=confirm.getText();
          
               
                String old = old_pass.getText();
                String sql ="update new_user set user_password='"+value1+"' WHERE user_password='"+old+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Success");
                
                  }
                  catch (Exception e){
            
            }
                  
             }
                    new_pass.setText(null);
            old_pass.setText(null);
            confirm.setText(null);
               }

            else{
                
                JOptionPane.showMessageDialog(null, "Old Password Incorrect");
            
            }
        }
        
        else{
        
            JOptionPane.showMessageDialog(null, "New Password Incorrect");
        }
        
           
            
            
        }
            catch (Exception e){
            
            }
        }
    }//GEN-LAST:event_new_passKeyPressed

    private void confirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            String sql_1 = "select * from new_user where  user_password=?";
        try{
       
            
             String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         
             pst=conn.prepareStatement(sql_1);
            pst.setString(1, old_pass.getText());
         //   pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            
            
            if(rs.next() ){

                 int c = JOptionPane.showConfirmDialog(null,"Do you want to continue?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                
                String value1=confirm.getText();
          
               
                String old = old_pass.getText();
                String sql ="update new_user set user_password='"+value1+"' WHERE user_password='"+old+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Success");
                
                  }
                  catch (Exception e){
            
            }
                  
             }
                    new_pass.setText(null);
            old_pass.setText(null);
            confirm.setText(null);
               }

            else{
                
                JOptionPane.showMessageDialog(null, "Old Password Incorrect");
            
            }
        }
        
        else{
        
            JOptionPane.showMessageDialog(null, "New Password Incorrect");
        }
        
           
            
            
        }
            catch (Exception e){
            
            }
        }
    }//GEN-LAST:event_confirmKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            String sql_1 = "select * from new_user where  user_password=?";
        try{
       
            
             String old_1 = (new_pass.getText());
  
       String conf =(confirm.getText());
       
        if (old_1.equals(conf)){
         
             pst=conn.prepareStatement(sql_1);
            pst.setString(1, old_pass.getText());
         //   pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            
            
            if(rs.next() ){

                 int c = JOptionPane.showConfirmDialog(null,"Do you want to continue?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                
                String value1=confirm.getText();
          
               
                String old = old_pass.getText();
                String sql ="update new_user set user_password='"+value1+"' WHERE user_password='"+old+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Successfu");
                
                  }
                  catch (Exception e){
            
            }
                  
             }
                    new_pass.setText(null);
            old_pass.setText(null);
            confirm.setText(null);
               }

            else{
                
                JOptionPane.showMessageDialog(null, "Old Password Incorrect");
            
            }
        }
        
        else{
        
            JOptionPane.showMessageDialog(null, "New Password Incorrect");
        }
        
           
            
            
        }
            catch (Exception e){
            
            }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
              setVisible(false);
        Fogort_password  fp = new Fogort_password();
        fp.setVisible(true);
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField new_pass;
    private javax.swing.JTextField old_pass;
    // End of variables declaration//GEN-END:variables
}
