/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_pack;


import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author oSikaNi iSraeL
 */
public final class login_form extends javax.swing.JFrame {
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form login_form
     */
    public login_form() {
        
       conn = java_connection.getConnection();
        initComponents();
         
         
        connection.setVisible(false);
       no_connection.setVisible(false);
       
        lbl_up.setVisible(false);
        lbl_down.setVisible(false);
        jLabel7.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        login.setVisible(false);
        fogrt.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(false);
        password.setVisible(false);
          userName.setVisible(false);
           jLabel9.setVisible(false);
        
          
        userName.setBackground(new Color(0,0,0,0));
        password.setBackground(new Color(0,0,0,0));
        
       // detectNetworkLoss();

    }
    
  /*  private void detectNetworkLoss(){
        
        Thread timer = new Thread(){

            @Override()
            public void run(){
            
                for(;;){
                    
                    Socket socket = new Socket();
                    InetSocketAddress address = new InetSocketAddress("www.google.com",80);
                    
                    try{
                    
                        socket.connect(address);
                        jLabel11.setText("Connected");
                    }
                    catch(IOException e){
                        jLabel11.setText("not Connected");
                    }
                
                    try{
                    
                        sleep(100);
                    }
                    catch(InterruptedException e){
                        e.printStackTrace();
                    }
                }
                
            }
        };
        timer.start();
    
    }*/
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_down = new javax.swing.JLabel();
        lbl_up = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sleep = new javax.swing.JLabel();
        fogrt = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        no_connection = new javax.swing.JLabel();
        connection = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_down.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lbl_down.setForeground(new java.awt.Color(255, 0, 0));
        lbl_down.setText("*");
        getContentPane().add(lbl_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 20, 30));

        lbl_up.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lbl_up.setForeground(new java.awt.Color(255, 0, 0));
        lbl_up.setText("*");
        getContentPane().add(lbl_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 20, 30));

        userName.setBackground(new java.awt.Color(201, 235, 210));
        userName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 0, 0));
        userName.setBorder(null);
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameKeyPressed(evt);
            }
        });
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 280, 40));

        password.setBackground(new java.awt.Color(222, 241, 226));
        password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 280, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 280, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 280, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setText("Login");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 40, 30));

        sleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sleep Mode_15px.png"))); // NOI18N
        sleep.setToolTipText("Sleep");
        sleep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sleep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sleepMouseClicked(evt);
            }
        });
        getContentPane().add(sleep, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        fogrt.setBackground(new java.awt.Color(189, 228, 196));
        fogrt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fogrt.setForeground(new java.awt.Color(0, 0, 0));
        fogrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Forgot Password_15px.png"))); // NOI18N
        fogrt.setText("Forgot Password");
        fogrt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fogrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fogrtActionPerformed(evt);
            }
        });
        getContentPane().add(fogrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        login.setBackground(new java.awt.Color(189, 228, 196));
        login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(0, 0, 0));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Login_15px.png"))); // NOI18N
        login.setText("Login");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        jButton1.setToolTipText("Click to Login");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, 130));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Minus_15px_1.png"))); // NOI18N
        jLabel14.setToolTipText("Minimize");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, -1));

        no_connection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/No Connection_20px_2.png"))); // NOI18N
        no_connection.setToolTipText("No internet Acces");
        no_connection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(no_connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        connection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Signal_20px_1.png"))); // NOI18N
        connection.setToolTipText("Internet Acces");
        connection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px_4.png"))); // NOI18N
        jLabel2.setToolTipText("Close");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 20, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User_100px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Password_20px_5.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 20, 40));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Male User_20px_3.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 20, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 420, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Loading");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("HOSTEL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 230));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 80)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 0));
        jLabel8.setText("JODOK");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newLOginBack.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 860, 580));

        setSize(new java.awt.Dimension(859, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
        
        lbl_up.setVisible(false);
        lbl_down.setVisible(false);
        
        if(userName.getText().equals("")){
        
        lbl_up.setVisible(true);
        
        }
       if(String.valueOf(password.getPassword()).equals("")){
    
            lbl_down.setVisible(true);
    }
       
       else{
    
       
         //  internet_connection();
              String sql = "select * from new_user where  username=? and user_password=?";
        try{
       
            pst=conn.prepareStatement(sql);
            pst.setString(1, userName.getText());
            pst.setString(2, password.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
            rs.close();
            pst.close();
            
            setVisible(false);
            loadingPage on = new loadingPage();
            on.setUpLoading1();
            on.setVisible(true);
            
      
            }
            
            else {
            
                JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                userName.setText(null);
                password.setText(null);
                
            }
       
        }
        
        catch(Exception e){
        
     //   JOptionPane.showMessageDialog(null, "Check your internet connection","No internet",JOptionPane.ERROR_MESSAGE);
        }
       
     
         
        
        finally{
        
            try{
            rs.close();
            pst.close();
            
        }
        catch(Exception e){
                
                
                }

        } 
       }
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void userNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             lbl_up.setVisible(false);
        lbl_down.setVisible(false);
        
        if(userName.getText().equals("")){
        
        lbl_up.setVisible(true);
        
        }
       if(String.valueOf(password.getPassword()).equals("")){
    
            lbl_down.setVisible(true);
    }
       
       else{
    
       
         //  internet_connection();
              String sql = "select * from new_user where  username=? and user_password=?";
        try{
       
            pst=conn.prepareStatement(sql);
            pst.setString(1, userName.getText());
            pst.setString(2, password.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
            rs.close();
            pst.close();
            
            setVisible(false);
            loadingPage on = new loadingPage();
            on.setUpLoading1();
            on.setVisible(true);
            
      
            }
            
            else {
            
                JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                userName.setText(null);
                password.setText(null);
                
            }
       
        }
        
        catch(Exception e){
        
     //   JOptionPane.showMessageDialog(null, "Check your internet connection","No internet",JOptionPane.ERROR_MESSAGE);
        }
       
     
         
        
        finally{
        
            try{
            rs.close();
            pst.close();
            
        }
        catch(Exception e){
                
                
                }

        } 
       }    
        }
    }//GEN-LAST:event_userNameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             lbl_up.setVisible(false);
        lbl_down.setVisible(false);
        
        if(userName.getText().equals("")){
        
        lbl_up.setVisible(true);
        
        }
       if(String.valueOf(password.getPassword()).equals("")){
    
            lbl_down.setVisible(true);
    }
       
       else{
    
       
         //  internet_connection();
              String sql = "select * from new_user where  username=? and user_password=?";
        try{
       
            pst=conn.prepareStatement(sql);
            pst.setString(1, userName.getText());
            pst.setString(2, password.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
            rs.close();
            pst.close();
            
            setVisible(false);
            loadingPage on = new loadingPage();
            on.setUpLoading1();
            on.setVisible(true);
            
      
            }
            
            else {
            
                JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                userName.setText(null);
                password.setText(null);
                
            }
       
        }
        
        catch(Exception e){
        
     //   JOptionPane.showMessageDialog(null, "Check your internet connection","No internet",JOptionPane.ERROR_MESSAGE);
        }
       
     
         
        
        finally{
        
            try{
            rs.close();
            pst.close();
            
        }
        catch(Exception e){
                
                
                }

        } 
       }    
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
         sleep.setEnabled(true);
        jLabel9.setVisible(true);
         jLabel10.setVisible(false);
         jButton1.setVisible(false);
         jLabel7.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        login.setVisible(true);
        fogrt.setVisible(true);
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
        password.setVisible(true);
          userName.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sleepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleepMouseClicked
        // TODO add your handling code here:
        lbl_up.setVisible(false);
        lbl_down.setVisible(false);
        sleep.setEnabled(false);
         jLabel9.setVisible(false);
         jLabel10.setVisible(true);
         jButton1.setVisible(true);
         jLabel7.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        login.setVisible(false);
        fogrt.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(false);
        password.setVisible(false);
          userName.setVisible(false);
          userName.setText(null);
          password.setText(null);
          
          
    }//GEN-LAST:event_sleepMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         sleep.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        // TODO add your handling code here:
        
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             lbl_up.setVisible(false);
        lbl_down.setVisible(false);
        
        if(userName.getText().equals("")){
        
        lbl_up.setVisible(true);
        
        }
       if(String.valueOf(password.getPassword()).equals("")){
    
            lbl_down.setVisible(true);
    }
       
       else{
    
       
         //  internet_connection();
              String sql = "select * from new_user where  username=? and user_password=?";
        try{
       
            pst=conn.prepareStatement(sql);
            pst.setString(1, userName.getText());
            pst.setString(2, password.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
            rs.close();
            pst.close();
            
            setVisible(false);
            loadingPage on = new loadingPage();
            on.setUpLoading1();
            on.setVisible(true);
            
      
            }
            
            else {
            
                JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                userName.setText(null);
                password.setText(null);
                
            }
       
        }
        
        catch(Exception e){
        
     //   JOptionPane.showMessageDialog(null, "Check your internet connection","No internet",JOptionPane.ERROR_MESSAGE);
        }
       
     
         
        
        finally{
        
            try{
            rs.close();
            pst.close();
            
        }
        catch(Exception e){
                
                
                }

        } 
       }    
        }
    }//GEN-LAST:event_loginKeyPressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void fogrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fogrtActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Fogort_password fp = new Fogort_password();
        fp.setVisible(true);
    }//GEN-LAST:event_fogrtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connection;
    private javax.swing.JButton fogrt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_down;
    private javax.swing.JLabel lbl_up;
    private javax.swing.JButton login;
    private javax.swing.JLabel no_connection;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel sleep;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
