/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_pack;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


/**
 *
 * @author oSikaNi iSraeL
 */
public class new_info extends javax.swing.JFrame {
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form new_info
     */
    public new_info() {
        initComponents();

        conn = java_connection.getConnection();
        currentDate();
    }
    
    
        public void currentDate(){
    
    
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        date_txt.setText("  "+ year+"-"+(month+1)+"-"+day);
       
   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        date_txt = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        prog = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        bed = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        hostel_fee = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        phone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Male User_100px_4.png"))); // NOI18N
        d.setText("jLabel2");
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 100, 90));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 250, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 250, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 250, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 250, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 250, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 250, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 250, -1));

        date_txt.setEditable(false);
        date_txt.setBackground(new java.awt.Color(145, 216, 169));
        date_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date_txt.setForeground(new java.awt.Color(0, 0, 0));
        date_txt.setBorder(null);
        date_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date_txtKeyPressed(evt);
            }
        });
        getContentPane().add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 250, 30));

        lname.setBackground(new java.awt.Color(195, 230, 201));
        lname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lname.setBorder(null);
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameKeyPressed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 250, 30));

        prog.setBackground(new java.awt.Color(214, 239, 220));
        prog.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        prog.setBorder(null);
        prog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                progKeyPressed(evt);
            }
        });
        getContentPane().add(prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 250, 30));

        room.setBackground(new java.awt.Color(214, 239, 220));
        room.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        room.setBorder(null);
        room.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomKeyPressed(evt);
            }
        });
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 250, 30));

        bed.setBackground(new java.awt.Color(214, 239, 220));
        bed.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bed.setBorder(null);
        bed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bedKeyPressed(evt);
            }
        });
        getContentPane().add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 250, 30));

        fname.setBackground(new java.awt.Color(202, 229, 203));
        fname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fname.setBorder(null);
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 250, 30));

        hostel_fee.setBackground(new java.awt.Color(205, 234, 211));
        hostel_fee.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        hostel_fee.setBorder(null);
        hostel_fee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hostel_feeKeyPressed(evt);
            }
        });
        getContentPane().add(hostel_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 250, 30));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 250, -1));

        phone.setBackground(new java.awt.Color(170, 223, 183));
        phone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        phone.setBorder(null);
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 250, 30));

        jButton1.setBackground(new java.awt.Color(91, 199, 126));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Reset_20px.png"))); // NOI18N
        jButton1.setText("Reset");
        jButton1.setToolTipText("Clear all fields");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        jButton2.setBackground(new java.awt.Color(91, 199, 126));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_20px.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setToolTipText("Go back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, -1));

        jButton3.setBackground(new java.awt.Color(91, 199, 126));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add User Male_20px_1.png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.setToolTipText("Add information");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(0, 51, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 230));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("HOSTEL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 80)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 0));
        jLabel12.setText("JODOK");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Program:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Room No:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hostel Fee:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("First Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Bed No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 420, 560));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newLOginBack.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_border.png"))); // NOI18N
        jMenu1.setText("File");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_20px_2.png"))); // NOI18N
        jMenuItem2.setText("Close");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_20px.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_20px.png"))); // NOI18N
        jMenuItem3.setText("Back");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(856, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fname.setText(null);
        lname.setText(null);
        prog.setText(null);
        bed.setText(null);
        room.setText(null);
        hostel_fee.setText(null);
        phone.setText(null);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mainPage mp = new mainPage();
        mp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
                    JOptionPane.showMessageDialog(null," Success");
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_fnameKeyPressed

    private void lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_lnameKeyPressed

    private void progKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_progKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_progKeyPressed

    private void roomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_roomKeyPressed

    private void bedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bedKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_bedKeyPressed

    private void hostel_feeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hostel_feeKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_hostel_feeKeyPressed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_phoneKeyPressed

    private void date_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_txtKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_date_txtKeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_info where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_info(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login_form  lf = new login_form();
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mainPage mp = new mainPage();
        mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bed;
    private javax.swing.JLabel d;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hostel_fee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField prog;
    private javax.swing.JTextField room;
    // End of variables declaration//GEN-END:variables
}
