/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_pack;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


/**
 *
 * @author oSikaNi iSraeL
 */
public class new_info extends javax.swing.JFrame {
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    int xMouse;
    int yMouse;

    /**
     * Creates new form new_info
     */
    public new_info() {
        initComponents();

        conn = java_connection.getConnection();
        currentDate();
          fname.setBackground(new Color(0,0,0,0));
       lname.setBackground(new Color(0,0,0,0));
         prog.setBackground(new Color(0,0,0,0));
       room.setBackground(new Color(0,0,0,0));
         bed.setBackground(new Color(0,0,0,0));
       hostel_fee.setBackground(new Color(0,0,0,0));
         phone.setBackground(new Color(0,0,0,0));
       date_txt.setBackground(new Color(0,0,0,0));
       jTextPane3.setBackground(new Color(0,0,0,0));
        
    }
    
    
        public void currentDate(){
    
    
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        date_txt.setText("  "+ year+"-"+(month+1)+"-"+day);
       
   
    }
    
        
     /*   public void my_Arrears(){
        
            String hostel = String.valueOf(hostel_fee.getText());
            
            double new_hostel = Double.parseDouble(hostel);
            
            String arrears_1 = String.valueOf(amt_paying.getText());
            
            double new_arrears = Double.parseDouble(arrears_1);
            
            double amt_left = new_hostel-new_arrears;
            
            arrears.setText(Double.toString(amt_left));
        }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        d = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        date_txt = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        prog = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        bed = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        hostel_fee = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        phone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        minus_fill = new javax.swing.JLabel();
        logout_fill = new javax.swing.JLabel();
        logout_lite = new javax.swing.JLabel();
        cancel_lite = new javax.swing.JLabel();
        cancel_fill = new javax.swing.JLabel();
        back_lite = new javax.swing.JLabel();
        back_fill = new javax.swing.JLabel();
        help_lite = new javax.swing.JLabel();
        help_fill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBackground(new java.awt.Color(0, 102, 0));

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(0, 102, 0));
        jTextPane3.setBorder(null);
        jTextPane3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextPane3.setText("Add Button:\n\nFill all the neccessary information about the new \nhosteler and press enter or click the add button \nto add new hosteler\n\nReset Button:\n\nThe reset Button clear's every information \nprovided in the filed with just a single clik.\n\nBack Button:\n \nThis button takes you back to the previous page.");
        jTextPane3.setOpaque(false);
        jScrollPane5.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 350, 300));

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Male User_100px_4.png"))); // NOI18N
        d.setText("jLabel2");
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 110, 110));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 250, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 250, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 250, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 250, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 250, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 250, -1));

        date_txt.setEditable(false);
        date_txt.setBackground(new java.awt.Color(145, 216, 169));
        date_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date_txt.setForeground(new java.awt.Color(0, 0, 0));
        date_txt.setBorder(null);
        date_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date_txtKeyPressed(evt);
            }
        });
        getContentPane().add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 250, 30));

        lname.setBackground(new java.awt.Color(195, 230, 201));
        lname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lname.setBorder(null);
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameKeyPressed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 250, 30));

        prog.setBackground(new java.awt.Color(214, 239, 220));
        prog.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        prog.setBorder(null);
        prog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                progKeyPressed(evt);
            }
        });
        getContentPane().add(prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 250, 30));

        room.setBackground(new java.awt.Color(214, 239, 220));
        room.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        room.setBorder(null);
        room.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomKeyTyped(evt);
            }
        });
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 250, 30));

        bed.setBackground(new java.awt.Color(214, 239, 220));
        bed.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bed.setBorder(null);
        bed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bedKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bedKeyTyped(evt);
            }
        });
        getContentPane().add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 250, 30));

        fname.setBackground(new java.awt.Color(202, 229, 203));
        fname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fname.setBorder(null);
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 250, 30));

        hostel_fee.setBackground(new java.awt.Color(205, 234, 211));
        hostel_fee.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        hostel_fee.setBorder(null);
        hostel_fee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hostel_feeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hostel_feeKeyTyped(evt);
            }
        });
        getContentPane().add(hostel_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 250, 30));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 250, -1));

        phone.setBackground(new java.awt.Color(170, 223, 183));
        phone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        phone.setBorder(null);
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 250, 30));

        jButton1.setBackground(new java.awt.Color(91, 199, 126));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Reset_20px.png"))); // NOI18N
        jButton1.setText("Reset");
        jButton1.setToolTipText("Clear all fields");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));

        jButton2.setBackground(new java.awt.Color(91, 199, 126));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_20px.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setToolTipText("Go back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        jButton3.setBackground(new java.awt.Color(91, 199, 126));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add User Male_20px_1.png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.setToolTipText("Add information");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(0, 51, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 230));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 250, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("HOSTEL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 80)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 0));
        jLabel12.setText("JODOK");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Program:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Room No:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hostel Fee:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("First Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Bed No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 420, 580));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newLOginBack.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 560));

        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jPanel5.setBackground(new java.awt.Color(219, 231, 217));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Minus_15px_1.png"))); // NOI18N
        minimize.setToolTipText("Resize down");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel5.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, -1, 40));

        minus_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus_fill.png"))); // NOI18N
        minus_fill.setToolTipText("Resize down");
        minus_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minus_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_fillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minus_fillMouseEntered(evt);
            }
        });
        jPanel5.add(minus_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 20));

        logout_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_15px_3.png"))); // NOI18N
        logout_fill.setToolTipText("Logout");
        logout_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_fillMouseClicked(evt);
            }
        });
        jPanel5.add(logout_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        logout_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_15px_4.png"))); // NOI18N
        logout_lite.setToolTipText("Logout");
        logout_lite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_liteMouseExited(evt);
            }
        });
        jPanel5.add(logout_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        cancel_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px_4.png"))); // NOI18N
        cancel_lite.setToolTipText("Close");
        cancel_lite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_liteMouseExited(evt);
            }
        });
        jPanel5.add(cancel_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 20));

        cancel_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px_3.png"))); // NOI18N
        cancel_fill.setToolTipText("Close");
        cancel_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_fillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_fillMouseEntered(evt);
            }
        });
        jPanel5.add(cancel_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 20));

        back_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_15px_2.png"))); // NOI18N
        back_lite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_liteMouseExited(evt);
            }
        });
        jPanel5.add(back_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        back_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_15px_1.png"))); // NOI18N
        back_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_fillMouseClicked(evt);
            }
        });
        jPanel5.add(back_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        help_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_15px_1.png"))); // NOI18N
        help_lite.setToolTipText("");
        help_lite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                help_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                help_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                help_liteMouseExited(evt);
            }
        });
        jPanel5.add(help_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 20, 20));

        help_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_15px.png"))); // NOI18N
        help_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                help_fillMouseClicked(evt);
            }
        });
        jPanel5.add(help_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 20, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 20));

        setSize(new java.awt.Dimension(856, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fname.setText(null);
        lname.setText(null);
        prog.setText(null);
        bed.setText(null);
        room.setText(null);
        hostel_fee.setText(null);
        phone.setText(null);
     //   amt_paying.setText("0");

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mainPage mp = new mainPage();
        mp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                  
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    
           JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);           
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                 
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
              
              
            /*  try{
            
            String sql_2="Insert into payment(fname,lname,room_no,bed_no,hostel_fee,  amt_paid, arreas, date_) values (?,?,?,?,?,?,?,?)";
        pst=conn.prepareStatement(sql_2);
        
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                 
                    pst.setString(3, room.getText());
                    pst.setString(4, bed.getText());
                    pst.setString(5, hostel_fee.getText());
                    pst.setString(6, amt_paying.getText());
                    pst.setString(7, arrears.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
        
        
        
                    amt_paying.setText("0");
        }
        catch(Exception e){
        
        }*/
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
        
        
           
       
}
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_fnameKeyPressed

    private void lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_lnameKeyPressed

    private void progKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_progKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_progKeyPressed

    private void roomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomKeyPressed
        // TODO add your handling code here:
          
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_roomKeyPressed

    private void bedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bedKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_bedKeyPressed

    private void hostel_feeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hostel_feeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_hostel_feeKeyPressed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_phoneKeyPressed

    private void date_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_txtKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_date_txtKeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                  if(
        fname.getText().isEmpty()
        ||lname.getText().isEmpty()
        ||prog.getText().isEmpty()
        || room.getText().isEmpty()
        || bed.getText().isEmpty()
        || phone.getText().isEmpty()
        )
{

    JOptionPane.showMessageDialog(null, "Enter all Information");
    
}

else{

     String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next() ){
          
            JOptionPane.showMessageDialog(null, "Room or Bed Number is Already Occupied");
      
            }
            
            else { 
            
           
              try {
          
                
                    String sql = "Insert into new_hosteler(fname,lname,program,roo_no,bed_no,hostel_fee,  phone,date_reg) values (?,?,?,?,?,?,?,?)";
                    
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, fname.getText());
                    pst.setString(2, lname.getText());
                    pst.setString(3, prog.getText());
                    pst.setString(4, room.getText());
                    pst.setString(5, bed.getText());
                    pst.setString(6, hostel_fee.getText());
                    pst.setString(7, phone.getText());
                    pst.setString(8, date_txt.getText());
                    
                    pst.execute();
                   
                    JOptionPane.showMessageDialog(null," Success");
                    
                    fname.setText(null);
                    lname.setText(null);
                    prog.setText(null);
                    room.setText(null);
                    
                    bed.setText(null);
                    hostel_fee.setText(null);
                    phone.setText(null);
                    
          
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);
        }
                
            }
       
        }
        
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
           
       
}
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void roomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)
                || c == KeyEvent.VK_ENTER
                || c == KeyEvent.VK_DELETE
                || c == KeyEvent.VK_BACK_SPACE)){
        
        
            evt.consume();
        }
    }//GEN-LAST:event_roomKeyTyped

    private void bedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bedKeyTyped
        // TODO add your handling code here:
             char c = evt.getKeyChar();
        if(!(Character.isDigit(c)
                || c == KeyEvent.VK_ENTER
                || c == KeyEvent.VK_DELETE
                || c == KeyEvent.VK_BACK_SPACE)){
        
        
            evt.consume();
        }
    }//GEN-LAST:event_bedKeyTyped

    private void hostel_feeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hostel_feeKeyTyped
        // TODO add your handling code here:
             char c = evt.getKeyChar();
        if(!(Character.isDigit(c)
                || c == KeyEvent.VK_ENTER
                || c == KeyEvent.VK_DELETE
                || c == KeyEvent.VK_BACK_SPACE)){
        
        
            evt.consume();
        }
    }//GEN-LAST:event_hostel_feeKeyTyped

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        // TODO add your handling code here:
             char c = evt.getKeyChar();
        if(!(Character.isDigit(c)
                || c == KeyEvent.VK_ENTER
                || c == KeyEvent.VK_DELETE
                || c == KeyEvent.VK_BACK_SPACE)){
        
        
            evt.consume();
        }
    }//GEN-LAST:event_phoneKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jScrollPane5.setVisible(false);
        
         help_fill.setVisible(false);
        minus_fill.setVisible(false);
        cancel_fill.setVisible(false);
        logout_fill.setVisible(false);
        back_fill.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         jScrollPane5.setVisible(false);
         
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         jScrollPane5.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:

        minus_fill.setVisible(true);
        minimize.setVisible(false);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:

        minus_fill.setVisible(false);
        minimize.setVisible(true);
    }//GEN-LAST:event_minimizeMouseExited

    private void minus_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_fillMouseClicked
        // TODO add your handling code here:

        this.setState(ICONIFIED);
    }//GEN-LAST:event_minus_fillMouseClicked

    private void minus_fillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_fillMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_minus_fillMouseEntered

    private void logout_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_fillMouseClicked
        // TODO add your handling code here:

        setVisible(false);
        login_form lf = new login_form();
        lf.setVisible(true);
    }//GEN-LAST:event_logout_fillMouseClicked

    private void logout_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_liteMouseClicked
        // TODO add your handling code here:

        setVisible(false);
        login_form lf = new login_form();
        lf.setVisible(true);
    }//GEN-LAST:event_logout_liteMouseClicked

    private void logout_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_liteMouseEntered
        // TODO add your handling code here:

        logout_fill.setVisible(true);
        logout_lite.setVisible(false);
    }//GEN-LAST:event_logout_liteMouseEntered

    private void logout_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_liteMouseExited
        // TODO add your handling code here:

        logout_fill.setVisible(false);
        logout_lite.setVisible(true);
    }//GEN-LAST:event_logout_liteMouseExited

    private void cancel_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_liteMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_cancel_liteMouseClicked

    private void cancel_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_liteMouseEntered
        // TODO add your handling code here:
        cancel_fill.setToolTipText("Close");
        cancel_fill.setVisible(true);

        cancel_lite.setVisible(false);
        cancel_lite.setToolTipText("Close");
    }//GEN-LAST:event_cancel_liteMouseEntered

    private void cancel_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_liteMouseExited
        // TODO add your handling code here:
        cancel_fill.setVisible(false);
        cancel_lite.setVisible(true);
    }//GEN-LAST:event_cancel_liteMouseExited

    private void cancel_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_fillMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancel_fillMouseClicked

    private void cancel_fillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_fillMouseEntered
        // TODO add your handling code here:
        cancel_fill.setToolTipText("Close");
    }//GEN-LAST:event_cancel_fillMouseEntered

    private void back_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_liteMouseClicked
        // TODO add your handling code here:

        setVisible(false);
        mainPage lf = new mainPage();
        lf.setVisible(true);
    }//GEN-LAST:event_back_liteMouseClicked

    private void back_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_liteMouseEntered
        // TODO add your handling code here:
        back_fill.setVisible(true);
        back_lite.setVisible(false);
    }//GEN-LAST:event_back_liteMouseEntered

    private void back_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_liteMouseExited
        // TODO add your handling code here:
        back_fill.setVisible(false);
        back_lite.setVisible(true);
    }//GEN-LAST:event_back_liteMouseExited

    private void back_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_fillMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        mainPage lf = new mainPage();
        lf.setVisible(true);
    }//GEN-LAST:event_back_fillMouseClicked

    private void help_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_liteMouseEntered
        // TODO add your handling code here:
        help_fill.setVisible(true);
        help_lite.setVisible(false);
    }//GEN-LAST:event_help_liteMouseEntered

    private void help_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_liteMouseExited
        // TODO add your handling code here:
        help_fill.setVisible(false);
        help_lite.setVisible(true);
    }//GEN-LAST:event_help_liteMouseExited

    private void help_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_liteMouseClicked
        // TODO add your handling code here:
        jScrollPane5.setVisible(true);
    }//GEN-LAST:event_help_liteMouseClicked

    private void help_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_fillMouseClicked
        // TODO add your handling code here:
        jScrollPane5.setVisible(true);
    }//GEN-LAST:event_help_fillMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        jScrollPane5.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             fname.setText(null);
        lname.setText(null);
        prog.setText(null);
        bed.setText(null);
        room.setText(null);
        hostel_fee.setText(null);
        phone.setText(null);
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
            setVisible(false);
        mainPage mp = new mainPage();
        mp.setVisible(true);
        }
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_fill;
    private javax.swing.JLabel back_lite;
    private javax.swing.JTextField bed;
    private javax.swing.JLabel cancel_fill;
    private javax.swing.JLabel cancel_lite;
    private javax.swing.JLabel d;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel help_fill;
    private javax.swing.JLabel help_lite;
    private javax.swing.JTextField hostel_fee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel logout_fill;
    private javax.swing.JLabel logout_lite;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel minus_fill;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField prog;
    private javax.swing.JTextField room;
    // End of variables declaration//GEN-END:variables
}
