/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_pack;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.text.MessageFormat;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author oSikaNi iSraeL
 */
public class update_info extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
     DefaultTableModel model_1;

    /**
     * Creates new form update_info
     */
    public update_info() {
        conn = java_connection.getConnection();
        initComponents();
       id.setVisible(false);
        
        Update_table();
    }
    
    private void filter (String sql){
    
          model_1 =(DefaultTableModel) jTable1.getModel();
     
         TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model_1);
         jTable1.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter(sql));
     }
    
     private void Update_table(){
    
        try {
          String sql ="SELECT hosteler_id as 'ID ',fname as 'First Name',lname as ' Last Name', program as 'Program', roo_no as 'Room No:',"
                  + " bed_no as 'Bird No:', hostel_fee as 'Hostel Fee', phone as 'Phone Number', date_reg as 'Date Registered' FROM new_hosteler ";
            pst=conn.prepareStatement(sql);
            
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
     //       JOptionPane.showMessageDialog( null, "You Cant update Information without Internet","Infomation",JOptionPane.PLAIN_MESSAGE);
        }
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        update_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        hostel_fee = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        room = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bed = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        prog = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        search_box = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        referesh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        minus_fill = new javax.swing.JLabel();
        logout_fill = new javax.swing.JLabel();
        logout_lite = new javax.swing.JLabel();
        cancel_lite = new javax.swing.JLabel();
        cancel_fill = new javax.swing.JLabel();
        back_lite = new javax.swing.JLabel();
        back_fill = new javax.swing.JLabel();
        help_lite = new javax.swing.JLabel();
        help_fill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 120));

        jTable1.setBackground(new java.awt.Color(187, 224, 190));
        jTable1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setRowMargin(2);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 890, 460));

        update_btn.setBackground(new java.awt.Color(213, 229, 216));
        update_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(0, 0, 0));
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit Property_20px_2.png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.setBorderPainted(false);
        update_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 100, 30));

        jButton2.setBackground(new java.awt.Color(213, 229, 216));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash_20px.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 100, 30));

        jButton3.setBackground(new java.awt.Color(213, 229, 216));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Print_20px_3.png"))); // NOI18N
        jButton3.setText("Print");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, -1, 30));

        save_btn.setBackground(new java.awt.Color(202, 229, 203));
        save_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        save_btn.setForeground(new java.awt.Color(0, 0, 0));
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_20px_1.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.setBorderPainted(false);
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 82, 12));
        jLabel5.setText("H O S T E L");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 210, 70));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 470, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 82, 12));
        jLabel4.setText("J O D O K ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 440, 70));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 180, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, -1, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 180, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, 180, -1));

        fname.setBackground(new java.awt.Color(202, 229, 203));
        fname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fname.setBorder(null);
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 180, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Bed No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 180, -1));

        hostel_fee.setBackground(new java.awt.Color(205, 234, 211));
        hostel_fee.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        hostel_fee.setBorder(null);
        getContentPane().add(hostel_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 180, 30));

        phone.setBackground(new java.awt.Color(170, 223, 183));
        phone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        phone.setBorder(null);
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Room No:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        lname.setBackground(new java.awt.Color(195, 230, 201));
        lname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lname.setBorder(null);
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 180, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/More Info_100px.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Program:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, -1, -1));

        room.setBackground(new java.awt.Color(214, 239, 220));
        room.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        room.setBorder(null);
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 180, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Hostel Fee:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, -1, -1));

        bed.setBackground(new java.awt.Color(214, 239, 220));
        bed.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bed.setBorder(null);
        getContentPane().add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 180, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 180, -1));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, 180, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Date:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, -1, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 180, -1));

        prog.setBackground(new java.awt.Color(214, 239, 220));
        prog.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        prog.setBorder(null);
        getContentPane().add(prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 180, 30));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 220, -1));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 180, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("First Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search_20px_3.png"))); // NOI18N
        jLabel14.setText("Search:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, 180, 30));

        search_box.setBackground(new java.awt.Color(213, 229, 216));
        search_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        search_box.setForeground(new java.awt.Color(0, 0, 0));
        search_box.setBorder(null);
        search_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_boxKeyReleased(evt);
            }
        });
        getContentPane().add(search_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 220, 40));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 100, -1));

        referesh.setBackground(new java.awt.Color(213, 229, 216));
        referesh.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        referesh.setForeground(new java.awt.Color(0, 0, 0));
        referesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh_20px.png"))); // NOI18N
        referesh.setText("Refresh");
        referesh.setBorderPainted(false);
        referesh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        referesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refereshActionPerformed(evt);
            }
        });
        getContentPane().add(referesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/31.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1200, 630));

        jPanel3.setBackground(new java.awt.Color(219, 231, 217));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Minus_15px_1.png"))); // NOI18N
        minimize.setToolTipText("Resize down");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel3.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, -1, 40));

        minus_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus_fill.png"))); // NOI18N
        minus_fill.setToolTipText("Resize down");
        minus_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minus_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_fillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minus_fillMouseEntered(evt);
            }
        });
        jPanel3.add(minus_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 20));

        logout_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_15px_3.png"))); // NOI18N
        logout_fill.setToolTipText("Logout");
        logout_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_fillMouseClicked(evt);
            }
        });
        jPanel3.add(logout_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        logout_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_15px_4.png"))); // NOI18N
        logout_lite.setToolTipText("Logout");
        logout_lite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_liteMouseExited(evt);
            }
        });
        jPanel3.add(logout_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        cancel_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px_4.png"))); // NOI18N
        cancel_lite.setToolTipText("Close");
        cancel_lite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_liteMouseExited(evt);
            }
        });
        jPanel3.add(cancel_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 20));

        cancel_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px_3.png"))); // NOI18N
        cancel_fill.setToolTipText("Close");
        cancel_fill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_fillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_fillMouseEntered(evt);
            }
        });
        jPanel3.add(cancel_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 20));

        back_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_15px_2.png"))); // NOI18N
        back_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_liteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_liteMouseExited(evt);
            }
        });
        jPanel3.add(back_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        back_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_15px_1.png"))); // NOI18N
        back_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_fillMouseClicked(evt);
            }
        });
        jPanel3.add(back_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        help_lite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_15px_1.png"))); // NOI18N
        help_lite.setToolTipText("");
        help_lite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                help_liteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                help_liteMouseExited(evt);
            }
        });
        jPanel3.add(help_lite, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, 20));

        help_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_15px.png"))); // NOI18N
        jPanel3.add(help_fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 20));

        setSize(new java.awt.Dimension(1199, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
         help_fill.setVisible(false);
        minus_fill.setVisible(false);
        cancel_fill.setVisible(false);
        logout_fill.setVisible(false);
        back_fill.setVisible(false);

                jSeparator10.setVisible(false);
        jSeparator2.setEnabled(false);
        jSeparator3.setEnabled(false);
        jSeparator4.setEnabled(false);
        jSeparator5.setEnabled(false);
        jSeparator6.setEnabled(false);
        jSeparator8.setEnabled(false);
        jSeparator6.setEnabled(false);
        fname.setEnabled(false);
        lname.setEnabled(false);
        prog.setEnabled(false);
        room.setEnabled(false);
        bed.setEnabled(false);
        hostel_fee.setEnabled(false);
        phone.setEnabled(false);
        jDateChooser1.setEnabled(false);
        update_btn.setEnabled(false);
        jLabel13.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel10.setEnabled(false);
        jLabel6.setEnabled(false);
        jLabel7.setEnabled(false);
        jLabel11.setEnabled(false);
        jLabel8.setEnabled(false);
        jLabel12.setEnabled(false);
        jLabel9.setEnabled(false);
        save_btn.setEnabled(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        save_btn.setEnabled(true);
          jSeparator10.setEnabled(true);
        jSeparator2.setEnabled(true);
        jSeparator3.setEnabled(true);
        jSeparator4.setEnabled(true);
        jSeparator5.setEnabled(true);
        jSeparator6.setEnabled(true);
        jSeparator8.setEnabled(true);
        jSeparator6.setEnabled(true);
        fname.setEnabled(true);
        lname.setEnabled(true);
        prog.setEnabled(true);
        room.setEnabled(true);
        bed.setEnabled(true);
        hostel_fee.setEnabled(true);
        phone.setEnabled(true);
        jDateChooser1.setEnabled(true);
        jLabel13.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel10.setEnabled(true);
        jLabel6.setEnabled(true);
        jLabel7.setEnabled(true);
        jLabel11.setEnabled(true);
        jLabel8.setEnabled(true);
        jLabel12.setEnabled(true);
        jLabel9.setEnabled(true);
    }//GEN-LAST:event_update_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        update_btn.setEnabled(true);
        
        try{

            int row = jTable1.getSelectedRow();
            String Table_click=(jTable1.getModel().getValueAt(row,0).toString());

            String sql ="SELECT * FROM new_hosteler WHERE hosteler_id = '"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){

                String id_ = rs.getString("hosteler_id");
                id.setText(id_);
                
                String f_name = rs.getString("fname");
                fname.setText(f_name);
                
                String l_name = rs.getString("lname");
                lname.setText(l_name);
                String progra = rs.getString("program");
                prog.setText(progra);
                
                String room2 = rs.getString("roo_no");
                room.setText(room2);
                
                String berd = rs.getString("bed_no");
                bed.setText(berd);
                
                String hostel = rs.getString("hostel_fee");
                hostel_fee.setText(hostel);
                
                String phone_no = rs.getString("phone");
                phone.setText(phone_no);
                
                String date = rs.getString("date_reg");
              
                ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText(date);
                
               
   
            }

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            finally{
        
        try{
         rs.close();
         pst.close();
        }
        catch(Exception e){
        
        
        }}
    }//GEN-LAST:event_jTable1MouseClicked

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:

          String sql_1 = "select * from new_hosteler where  roo_no=? and bed_no=?";
        try{
       
            pst=conn.prepareStatement(sql_1);
            pst.setString(1, room.getText());
            pst.setString(2, bed.getText());
            
            rs=pst.executeQuery();
            
            
            if(rs.next() ){
                //JOptionPane.showMessageDialog(null, "Room or Bed Numbers Already Occupied");
                int c = JOptionPane.showConfirmDialog(null,"Room or Bed Number is already Occupied\nDo you want to continue?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                String value1=id.getText();
                String value2=fname.getText();
                String value3=lname.getText();
                String value4=prog.getText();
                String value5=room.getText();
                String value6=bed.getText();
                String value7= hostel_fee.getText();
                String value8=phone.getText();
                String value9=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
               

                String sql ="update new_hosteler set hosteler_id='"+value1+"', fname='"+value2+"', "
                        + "lname='"+value3+"', program='"+value4+"', roo_no='"+value5+"',"
                        + "bed_no='"+value6+"', hostel_fee='"+value7+"', phone='"+value8+"',"
                        + "date_reg='"+value9+"'  where hosteler_id='"+value1+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Update Successful");
                
               
                
             fname.setText(null);
        lname.setText(null);
        prog.setText(null);
        room.setText(null);
        bed.setText(null);
        hostel_fee.setText(null);
        phone.setText(null);
        jDateChooser1.setDate(null);
            }

            catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }
              finally{
        
        try{
         rs.close();
         pst.close();
        }
        catch(Exception e){
        
        
        }}
             
             }
            }
            
            else{
          
             int c = JOptionPane.showConfirmDialog(null,"Confirm?","Confrim",JOptionPane.YES_NO_OPTION);
             if(c==0){
             
                  try{
                String value1=id.getText();
                String value2=fname.getText();
                String value3=lname.getText();
                String value4=prog.getText();
                String value5=room.getText();
                String value6=bed.getText();
                String value7= hostel_fee.getText();
                String value8=phone.getText();
                String value9=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
               

                String sql ="update new_info set customer_id='"+value1+"', fname='"+value2+"', "
                        + "lname='"+value3+"', program='"+value4+"', roo_no='"+value5+"',"
                        + "bed_no='"+value6+"', hostel_fee='"+value7+"', phone='"+value8+"',"
                        + "date_reg='"+value9+"'  where customer_id='"+value1+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Update Successful");
                
               
                
             fname.setText(null);
        lname.setText(null);
        prog.setText(null);
        room.setText(null);
        bed.setText(null);
        hostel_fee.setText(null);
        phone.setText(null);
        jDateChooser1.setDate(null);
            }

            catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }
              finally{
        
        try{
         rs.close();
         pst.close();
        }
        catch(Exception e){
        
        
        }}
             
             }
            }
         
        }
            catch(Exception e){
                    
                    }
        
               
            
            
        
        
        
    }//GEN-LAST:event_save_btnActionPerformed

    private void refereshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refereshActionPerformed
        // TODO add your handling code here:
        Update_table();
        fname.setText(null);
        lname.setText(null);
        prog.setText(null);
        room.setText(null);
        bed.setText(null);
        hostel_fee.setText(null);
        phone.setText(null);
        jDateChooser1.setDate(null);
        fname.setEnabled(false);
        lname.setEnabled(false);
        prog.setEnabled(false);
        room.setEnabled(false);
        bed.setEnabled(false);
        hostel_fee.setEnabled(false);
        phone.setEnabled(false);
        jDateChooser1.setEnabled(false);
        update_btn.setEnabled(false);
    }//GEN-LAST:event_refereshActionPerformed

    private void search_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyReleased
        // TODO add your handling code here:
         
        String txt=search_box.getText();
        filter (txt);
    }//GEN-LAST:event_search_boxKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int row=jTable1.getSelectedRow();
            
            if(row==-1){
                
                JOptionPane.showMessageDialog(null, "No Row Selected");
            
            }
            else{
                
                 int c = JOptionPane.showConfirmDialog(null, "Do you realy wanna Delete","Delete",JOptionPane.YES_NO_OPTION);
      
        if(c==0){
        String sql =" DELETE FROM new_hosteler WHERE hosteler_id =?";
        try{
        
            pst=conn.prepareStatement(sql);
            pst.setString(1,id.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, " Deleted Successfully");
            
    
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        }
        
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         MessageFormat header = new MessageFormat("All Student Summary");
         MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
        try{
             
             jTable1.print(JTable.PrintMode.NORMAL, header, footer);


    }catch(Exception e)
    {
           System.err.format("Cannont print %s%n",e.getMessage());

    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:

        minus_fill.setVisible(true);
        minimize.setVisible(false);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:

        minus_fill.setVisible(false);
        minimize.setVisible(true);
    }//GEN-LAST:event_minimizeMouseExited

    private void minus_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_fillMouseClicked
        // TODO add your handling code here:

        this.setState(ICONIFIED);
    }//GEN-LAST:event_minus_fillMouseClicked

    private void minus_fillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_fillMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_minus_fillMouseEntered

    private void logout_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_fillMouseClicked
        // TODO add your handling code here:

        setVisible(false);
        login_form lf = new login_form();
        lf.setVisible(true);
    }//GEN-LAST:event_logout_fillMouseClicked

    private void logout_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_liteMouseClicked
        // TODO add your handling code here:

        setVisible(false);
        login_form lf = new login_form();
        lf.setVisible(true);
    }//GEN-LAST:event_logout_liteMouseClicked

    private void logout_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_liteMouseEntered
        // TODO add your handling code here:

        logout_fill.setVisible(true);
        logout_lite.setVisible(false);
    }//GEN-LAST:event_logout_liteMouseEntered

    private void logout_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_liteMouseExited
        // TODO add your handling code here:

        logout_fill.setVisible(false);
        logout_lite.setVisible(true);
    }//GEN-LAST:event_logout_liteMouseExited

    private void cancel_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_liteMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_cancel_liteMouseClicked

    private void cancel_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_liteMouseEntered
        // TODO add your handling code here:
        cancel_fill.setToolTipText("Close");
        cancel_fill.setVisible(true);

        cancel_lite.setVisible(false);
        cancel_lite.setToolTipText("Close");
    }//GEN-LAST:event_cancel_liteMouseEntered

    private void cancel_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_liteMouseExited
        // TODO add your handling code here:
        cancel_fill.setVisible(false);
        cancel_lite.setVisible(true);
    }//GEN-LAST:event_cancel_liteMouseExited

    private void cancel_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_fillMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancel_fillMouseClicked

    private void cancel_fillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_fillMouseEntered
        // TODO add your handling code here:
        cancel_fill.setToolTipText("Close");
    }//GEN-LAST:event_cancel_fillMouseEntered

    private void back_liteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_liteMouseClicked
        // TODO add your handling code here:

        setVisible(false);
        mainPage lf = new mainPage();
        lf.setVisible(true);
    }//GEN-LAST:event_back_liteMouseClicked

    private void back_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_liteMouseEntered
        // TODO add your handling code here:
        back_fill.setVisible(true);
        back_lite.setVisible(false);
    }//GEN-LAST:event_back_liteMouseEntered

    private void back_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_liteMouseExited
        // TODO add your handling code here:
        back_fill.setVisible(false);
        back_lite.setVisible(true);
    }//GEN-LAST:event_back_liteMouseExited

    private void back_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_fillMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        mainPage lf = new mainPage();
        lf.setVisible(true);
    }//GEN-LAST:event_back_fillMouseClicked

    private void help_liteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_liteMouseEntered
        // TODO add your handling code here:
        help_fill.setVisible(true);
        help_lite.setVisible(false);
    }//GEN-LAST:event_help_liteMouseEntered

    private void help_liteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_liteMouseExited
        // TODO add your handling code here:
        help_fill.setVisible(false);
        help_lite.setVisible(true);
    }//GEN-LAST:event_help_liteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_fill;
    private javax.swing.JLabel back_lite;
    private javax.swing.JTextField bed;
    private javax.swing.JLabel cancel_fill;
    private javax.swing.JLabel cancel_lite;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel help_fill;
    private javax.swing.JLabel help_lite;
    private javax.swing.JTextField hostel_fee;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel logout_fill;
    private javax.swing.JLabel logout_lite;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel minus_fill;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField prog;
    private javax.swing.JButton referesh;
    private javax.swing.JTextField room;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField search_box;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
